### ISSUE TITLE
Aimbot Question

### ISSUE THREAD

**Issue by LiamSirBean** [CowNowK/AimStar#191]
What does the ragebot do because when I do aimbot it looks the same

**Comment by Amgtop** [comment]
When I push alt button for aim bot it jumps to the sky and please add always on on aimbot to do it without any buttons. Why there it no any enemy sensor on misc list

**Comment by M3351AN** [comment]
> When I push alt button for aim bot it jumps to the sky and please add always on on aimbot to do it without any buttons. Why there it no any enemy sensor on misc list

aimbot>aim lock

**Comment by CowNowK** [comment]
> 当我按下瞄准机器人的 alt 按钮时，它会跳到天空，请在 aimbot 上添加始终开启，无需任何按钮即可完成。为什么杂项列表中没有任何敌方传感器

at the bottom of esp

**Comment by 1thanks12** [comment]
> > 当我按下瞄准机器人的 alt 按钮时，它会跳到天空，请在 aimbot 上添加始终开启，无需任何按钮即可完成。为什么杂项列表中没有任何敌方传感器
> 
> at the bottom of esp

您好，请问自瞄功能能恢复到4.0.3版本那个方式吗？就像旧自瞄一样按下自瞄键在范围内就直接锁定到敌人头顶上。因为新的自瞄方式锁定不到敌人，安全模式下自动锁定准心对准敌人后画面会到处飘，甚至瞄向天空，启用红锁会导致游戏崩溃退出。希望能出一个像以前一样按下自瞄按键后就锁定到敌人，而且平滑度很低能马上把准心对准到敌人，谢谢！
Hello, can the self aiming function be restored to version 4.0.3? Just like the old self aiming, pressing the self aiming button within range will directly lock onto the enemy's head. Due to the new self aiming method not being able to lock enemies, the screen will float everywhere and even aim towards the sky after automatically locking the focus in safe mode. Enabling the red lock will cause the game to crash and exit. I hope to create a self aiming button like before that can lock in the enemy immediately after pressing it, and the smoothness is very low, so that the focus can be immediately aligned with the enemy. Thank you!
