### ISSUE TITLE
作者为什么要删除多语言啊！

### ISSUE THREAD

**Issue by 6KKK6** [CowNowK/AimStar#222]
作者能不能在新版本中加回多语言，我看不懂英文😭

**Comment by M3351AN** [comment]
Because most of the main maintainers (including me) are not native Chinese speakers, maintaining large amounts of multilingual content as functionality changes is complicated At the same time, based on the feedback I got, adding multiple languages ​​does not solve the problem of users not understanding the purpose of the feature.
由于大多数主要维护者（包括我）都不是中文母语，因此随着功能的变化维护大量的多语言内容是很复杂的
同时，根据我得到的反馈，添加多种语言并不能解决用户不理解该功能用途的问题。

**Comment by 6KKK6** [comment]
不能保存配置文件吗？为什么我每次玩都要重新设置😥

**Comment by CowNowK** [comment]
1. 维护麻烦
2. 大多数用户贡献语言之后就不再更新了，我不负责语言更新
3. 使得程序很臃肿
4. 大多数人在母语阅读上依旧存在理解困难的情况
